[package]
name = "journal"
version = "0.1.0"
entrypoint = "journal.typ"
authors = ["Jonathan Halmen <slowjo@halmen.xyz>"]
license = "MIT"
description = "An Abbreviations package."
repository = "https://github.com/abhinandh-s/journal.git"
keywords = ["abbreviation", "acronym"]
categories = ["model"]
exclude = ["example.*"]
